/**
 * SECURITY Domain Schemas and Rules Definitions
 * Enterprise Sales CRM security domain model specifications
 */

export interface SecurityConfig {
  id: string;
  name: string;
  enabled: boolean;
  version: string;
  description: string;
  maxRecords: number;
  retryAttempts: number;
  timeoutMs: number;
  auditEnabled: boolean;
}

export interface SecurityRule {
  id: string;
  code: string;
  name: string;
  category: 'security_validation' | 'security_automation' | 'security_compliance';
  expression: string;
  errorMessage: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  active: boolean;
}

export interface SecurityTaxonomy {
  categoryCode: string;
  displayName: string;
  subCategories: string[];
  tags: string[];
  metadata: Record<string, string | number | boolean>;
}

export const defaultSecurityConfigs: SecurityConfig[] = [
  {
    id: 'security-cfg-1',
    name: 'Standard Security Configuration Tier 1',
    enabled: true,
    version: '2.4.1',
    description: 'Enterprise operational settings for security tier 1 management.',
    maxRecords: 1000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-2',
    name: 'Standard Security Configuration Tier 2',
    enabled: true,
    version: '2.4.2',
    description: 'Enterprise operational settings for security tier 2 management.',
    maxRecords: 2000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-3',
    name: 'Standard Security Configuration Tier 3',
    enabled: true,
    version: '2.4.3',
    description: 'Enterprise operational settings for security tier 3 management.',
    maxRecords: 3000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-4',
    name: 'Standard Security Configuration Tier 4',
    enabled: true,
    version: '2.4.4',
    description: 'Enterprise operational settings for security tier 4 management.',
    maxRecords: 4000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-5',
    name: 'Standard Security Configuration Tier 5',
    enabled: true,
    version: '2.4.5',
    description: 'Enterprise operational settings for security tier 5 management.',
    maxRecords: 5000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-6',
    name: 'Standard Security Configuration Tier 6',
    enabled: true,
    version: '2.4.6',
    description: 'Enterprise operational settings for security tier 6 management.',
    maxRecords: 6000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-7',
    name: 'Standard Security Configuration Tier 7',
    enabled: true,
    version: '2.4.7',
    description: 'Enterprise operational settings for security tier 7 management.',
    maxRecords: 7000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-8',
    name: 'Standard Security Configuration Tier 8',
    enabled: true,
    version: '2.4.8',
    description: 'Enterprise operational settings for security tier 8 management.',
    maxRecords: 8000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-9',
    name: 'Standard Security Configuration Tier 9',
    enabled: true,
    version: '2.4.9',
    description: 'Enterprise operational settings for security tier 9 management.',
    maxRecords: 9000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-10',
    name: 'Standard Security Configuration Tier 10',
    enabled: true,
    version: '2.4.10',
    description: 'Enterprise operational settings for security tier 10 management.',
    maxRecords: 10000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-11',
    name: 'Standard Security Configuration Tier 11',
    enabled: true,
    version: '2.4.11',
    description: 'Enterprise operational settings for security tier 11 management.',
    maxRecords: 11000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-12',
    name: 'Standard Security Configuration Tier 12',
    enabled: true,
    version: '2.4.12',
    description: 'Enterprise operational settings for security tier 12 management.',
    maxRecords: 12000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-13',
    name: 'Standard Security Configuration Tier 13',
    enabled: true,
    version: '2.4.13',
    description: 'Enterprise operational settings for security tier 13 management.',
    maxRecords: 13000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-14',
    name: 'Standard Security Configuration Tier 14',
    enabled: true,
    version: '2.4.14',
    description: 'Enterprise operational settings for security tier 14 management.',
    maxRecords: 14000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-15',
    name: 'Standard Security Configuration Tier 15',
    enabled: true,
    version: '2.4.15',
    description: 'Enterprise operational settings for security tier 15 management.',
    maxRecords: 15000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-16',
    name: 'Standard Security Configuration Tier 16',
    enabled: true,
    version: '2.4.16',
    description: 'Enterprise operational settings for security tier 16 management.',
    maxRecords: 16000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-17',
    name: 'Standard Security Configuration Tier 17',
    enabled: true,
    version: '2.4.17',
    description: 'Enterprise operational settings for security tier 17 management.',
    maxRecords: 17000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-18',
    name: 'Standard Security Configuration Tier 18',
    enabled: true,
    version: '2.4.18',
    description: 'Enterprise operational settings for security tier 18 management.',
    maxRecords: 18000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-19',
    name: 'Standard Security Configuration Tier 19',
    enabled: true,
    version: '2.4.19',
    description: 'Enterprise operational settings for security tier 19 management.',
    maxRecords: 19000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-20',
    name: 'Standard Security Configuration Tier 20',
    enabled: true,
    version: '2.4.20',
    description: 'Enterprise operational settings for security tier 20 management.',
    maxRecords: 20000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-21',
    name: 'Standard Security Configuration Tier 21',
    enabled: true,
    version: '2.4.21',
    description: 'Enterprise operational settings for security tier 21 management.',
    maxRecords: 21000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-22',
    name: 'Standard Security Configuration Tier 22',
    enabled: true,
    version: '2.4.22',
    description: 'Enterprise operational settings for security tier 22 management.',
    maxRecords: 22000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-23',
    name: 'Standard Security Configuration Tier 23',
    enabled: true,
    version: '2.4.23',
    description: 'Enterprise operational settings for security tier 23 management.',
    maxRecords: 23000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-24',
    name: 'Standard Security Configuration Tier 24',
    enabled: true,
    version: '2.4.24',
    description: 'Enterprise operational settings for security tier 24 management.',
    maxRecords: 24000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-25',
    name: 'Standard Security Configuration Tier 25',
    enabled: true,
    version: '2.4.25',
    description: 'Enterprise operational settings for security tier 25 management.',
    maxRecords: 25000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-26',
    name: 'Standard Security Configuration Tier 26',
    enabled: true,
    version: '2.4.26',
    description: 'Enterprise operational settings for security tier 26 management.',
    maxRecords: 26000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-27',
    name: 'Standard Security Configuration Tier 27',
    enabled: true,
    version: '2.4.27',
    description: 'Enterprise operational settings for security tier 27 management.',
    maxRecords: 27000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-28',
    name: 'Standard Security Configuration Tier 28',
    enabled: true,
    version: '2.4.28',
    description: 'Enterprise operational settings for security tier 28 management.',
    maxRecords: 28000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-29',
    name: 'Standard Security Configuration Tier 29',
    enabled: true,
    version: '2.4.29',
    description: 'Enterprise operational settings for security tier 29 management.',
    maxRecords: 29000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-30',
    name: 'Standard Security Configuration Tier 30',
    enabled: true,
    version: '2.4.30',
    description: 'Enterprise operational settings for security tier 30 management.',
    maxRecords: 30000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-31',
    name: 'Standard Security Configuration Tier 31',
    enabled: true,
    version: '2.4.31',
    description: 'Enterprise operational settings for security tier 31 management.',
    maxRecords: 31000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-32',
    name: 'Standard Security Configuration Tier 32',
    enabled: true,
    version: '2.4.32',
    description: 'Enterprise operational settings for security tier 32 management.',
    maxRecords: 32000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-33',
    name: 'Standard Security Configuration Tier 33',
    enabled: true,
    version: '2.4.33',
    description: 'Enterprise operational settings for security tier 33 management.',
    maxRecords: 33000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-34',
    name: 'Standard Security Configuration Tier 34',
    enabled: true,
    version: '2.4.34',
    description: 'Enterprise operational settings for security tier 34 management.',
    maxRecords: 34000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'security-cfg-35',
    name: 'Standard Security Configuration Tier 35',
    enabled: true,
    version: '2.4.35',
    description: 'Enterprise operational settings for security tier 35 management.',
    maxRecords: 35000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
];

export const defaultSecurityRules: SecurityRule[] = [
  {
    id: 'security-rule-1',
    code: 'RUL_SECURITY_001',
    name: 'Validate Security Business Policy 1',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 1.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-2',
    code: 'RUL_SECURITY_002',
    name: 'Validate Security Business Policy 2',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 2.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'security-rule-3',
    code: 'RUL_SECURITY_003',
    name: 'Validate Security Business Policy 3',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 3.',
    severity: 'high',
    active: true,
  },
  {
    id: 'security-rule-4',
    code: 'RUL_SECURITY_004',
    name: 'Validate Security Business Policy 4',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 4.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'security-rule-5',
    code: 'RUL_SECURITY_005',
    name: 'Validate Security Business Policy 5',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 5.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-6',
    code: 'RUL_SECURITY_006',
    name: 'Validate Security Business Policy 6',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 6.',
    severity: 'high',
    active: true,
  },
  {
    id: 'security-rule-7',
    code: 'RUL_SECURITY_007',
    name: 'Validate Security Business Policy 7',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 7.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-8',
    code: 'RUL_SECURITY_008',
    name: 'Validate Security Business Policy 8',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 8.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'security-rule-9',
    code: 'RUL_SECURITY_009',
    name: 'Validate Security Business Policy 9',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 9.',
    severity: 'high',
    active: true,
  },
  {
    id: 'security-rule-10',
    code: 'RUL_SECURITY_010',
    name: 'Validate Security Business Policy 10',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 10.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'security-rule-11',
    code: 'RUL_SECURITY_011',
    name: 'Validate Security Business Policy 11',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 11.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-12',
    code: 'RUL_SECURITY_012',
    name: 'Validate Security Business Policy 12',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 12.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'security-rule-13',
    code: 'RUL_SECURITY_013',
    name: 'Validate Security Business Policy 13',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 13.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-14',
    code: 'RUL_SECURITY_014',
    name: 'Validate Security Business Policy 14',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 14.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'security-rule-15',
    code: 'RUL_SECURITY_015',
    name: 'Validate Security Business Policy 15',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 15.',
    severity: 'high',
    active: true,
  },
  {
    id: 'security-rule-16',
    code: 'RUL_SECURITY_016',
    name: 'Validate Security Business Policy 16',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 16.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'security-rule-17',
    code: 'RUL_SECURITY_017',
    name: 'Validate Security Business Policy 17',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 17.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-18',
    code: 'RUL_SECURITY_018',
    name: 'Validate Security Business Policy 18',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 18.',
    severity: 'high',
    active: true,
  },
  {
    id: 'security-rule-19',
    code: 'RUL_SECURITY_019',
    name: 'Validate Security Business Policy 19',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 19.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-20',
    code: 'RUL_SECURITY_020',
    name: 'Validate Security Business Policy 20',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 20.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'security-rule-21',
    code: 'RUL_SECURITY_021',
    name: 'Validate Security Business Policy 21',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 21.',
    severity: 'high',
    active: true,
  },
  {
    id: 'security-rule-22',
    code: 'RUL_SECURITY_022',
    name: 'Validate Security Business Policy 22',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 22.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'security-rule-23',
    code: 'RUL_SECURITY_023',
    name: 'Validate Security Business Policy 23',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 23.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-24',
    code: 'RUL_SECURITY_024',
    name: 'Validate Security Business Policy 24',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 24.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'security-rule-25',
    code: 'RUL_SECURITY_025',
    name: 'Validate Security Business Policy 25',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 25.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-26',
    code: 'RUL_SECURITY_026',
    name: 'Validate Security Business Policy 26',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 26.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'security-rule-27',
    code: 'RUL_SECURITY_027',
    name: 'Validate Security Business Policy 27',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 27.',
    severity: 'high',
    active: true,
  },
  {
    id: 'security-rule-28',
    code: 'RUL_SECURITY_028',
    name: 'Validate Security Business Policy 28',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 28.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'security-rule-29',
    code: 'RUL_SECURITY_029',
    name: 'Validate Security Business Policy 29',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 29.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-30',
    code: 'RUL_SECURITY_030',
    name: 'Validate Security Business Policy 30',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 30.',
    severity: 'high',
    active: true,
  },
  {
    id: 'security-rule-31',
    code: 'RUL_SECURITY_031',
    name: 'Validate Security Business Policy 31',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 31.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-32',
    code: 'RUL_SECURITY_032',
    name: 'Validate Security Business Policy 32',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 32.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'security-rule-33',
    code: 'RUL_SECURITY_033',
    name: 'Validate Security Business Policy 33',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 33.',
    severity: 'high',
    active: true,
  },
  {
    id: 'security-rule-34',
    code: 'RUL_SECURITY_034',
    name: 'Validate Security Business Policy 34',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 34.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'security-rule-35',
    code: 'RUL_SECURITY_035',
    name: 'Validate Security Business Policy 35',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 35.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-36',
    code: 'RUL_SECURITY_036',
    name: 'Validate Security Business Policy 36',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 36.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'security-rule-37',
    code: 'RUL_SECURITY_037',
    name: 'Validate Security Business Policy 37',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 37.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-38',
    code: 'RUL_SECURITY_038',
    name: 'Validate Security Business Policy 38',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 38.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'security-rule-39',
    code: 'RUL_SECURITY_039',
    name: 'Validate Security Business Policy 39',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 39.',
    severity: 'high',
    active: true,
  },
  {
    id: 'security-rule-40',
    code: 'RUL_SECURITY_040',
    name: 'Validate Security Business Policy 40',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 40.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'security-rule-41',
    code: 'RUL_SECURITY_041',
    name: 'Validate Security Business Policy 41',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 41.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-42',
    code: 'RUL_SECURITY_042',
    name: 'Validate Security Business Policy 42',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 42.',
    severity: 'high',
    active: true,
  },
  {
    id: 'security-rule-43',
    code: 'RUL_SECURITY_043',
    name: 'Validate Security Business Policy 43',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 43.',
    severity: 'low',
    active: true,
  },
  {
    id: 'security-rule-44',
    code: 'RUL_SECURITY_044',
    name: 'Validate Security Business Policy 44',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 44.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'security-rule-45',
    code: 'RUL_SECURITY_045',
    name: 'Validate Security Business Policy 45',
    category: 'security_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Security record fails compliance policy check 45.',
    severity: 'high',
    active: true,
  },
];
