/**
 * QUOTATIONS Domain Schemas and Rules Definitions
 * Enterprise Sales CRM quotations domain model specifications
 */

export interface QuotationsConfig {
  id: string;
  name: string;
  enabled: boolean;
  version: string;
  description: string;
  maxRecords: number;
  retryAttempts: number;
  timeoutMs: number;
  auditEnabled: boolean;
}

export interface QuotationsRule {
  id: string;
  code: string;
  name: string;
  category: 'quotations_validation' | 'quotations_automation' | 'quotations_compliance';
  expression: string;
  errorMessage: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  active: boolean;
}

export interface QuotationsTaxonomy {
  categoryCode: string;
  displayName: string;
  subCategories: string[];
  tags: string[];
  metadata: Record<string, string | number | boolean>;
}

export const defaultQuotationsConfigs: QuotationsConfig[] = [
  {
    id: 'quotations-cfg-1',
    name: 'Standard Quotations Configuration Tier 1',
    enabled: true,
    version: '2.4.1',
    description: 'Enterprise operational settings for quotations tier 1 management.',
    maxRecords: 1000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-2',
    name: 'Standard Quotations Configuration Tier 2',
    enabled: true,
    version: '2.4.2',
    description: 'Enterprise operational settings for quotations tier 2 management.',
    maxRecords: 2000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-3',
    name: 'Standard Quotations Configuration Tier 3',
    enabled: true,
    version: '2.4.3',
    description: 'Enterprise operational settings for quotations tier 3 management.',
    maxRecords: 3000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-4',
    name: 'Standard Quotations Configuration Tier 4',
    enabled: true,
    version: '2.4.4',
    description: 'Enterprise operational settings for quotations tier 4 management.',
    maxRecords: 4000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-5',
    name: 'Standard Quotations Configuration Tier 5',
    enabled: true,
    version: '2.4.5',
    description: 'Enterprise operational settings for quotations tier 5 management.',
    maxRecords: 5000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-6',
    name: 'Standard Quotations Configuration Tier 6',
    enabled: true,
    version: '2.4.6',
    description: 'Enterprise operational settings for quotations tier 6 management.',
    maxRecords: 6000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-7',
    name: 'Standard Quotations Configuration Tier 7',
    enabled: true,
    version: '2.4.7',
    description: 'Enterprise operational settings for quotations tier 7 management.',
    maxRecords: 7000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-8',
    name: 'Standard Quotations Configuration Tier 8',
    enabled: true,
    version: '2.4.8',
    description: 'Enterprise operational settings for quotations tier 8 management.',
    maxRecords: 8000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-9',
    name: 'Standard Quotations Configuration Tier 9',
    enabled: true,
    version: '2.4.9',
    description: 'Enterprise operational settings for quotations tier 9 management.',
    maxRecords: 9000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-10',
    name: 'Standard Quotations Configuration Tier 10',
    enabled: true,
    version: '2.4.10',
    description: 'Enterprise operational settings for quotations tier 10 management.',
    maxRecords: 10000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-11',
    name: 'Standard Quotations Configuration Tier 11',
    enabled: true,
    version: '2.4.11',
    description: 'Enterprise operational settings for quotations tier 11 management.',
    maxRecords: 11000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-12',
    name: 'Standard Quotations Configuration Tier 12',
    enabled: true,
    version: '2.4.12',
    description: 'Enterprise operational settings for quotations tier 12 management.',
    maxRecords: 12000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-13',
    name: 'Standard Quotations Configuration Tier 13',
    enabled: true,
    version: '2.4.13',
    description: 'Enterprise operational settings for quotations tier 13 management.',
    maxRecords: 13000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-14',
    name: 'Standard Quotations Configuration Tier 14',
    enabled: true,
    version: '2.4.14',
    description: 'Enterprise operational settings for quotations tier 14 management.',
    maxRecords: 14000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-15',
    name: 'Standard Quotations Configuration Tier 15',
    enabled: true,
    version: '2.4.15',
    description: 'Enterprise operational settings for quotations tier 15 management.',
    maxRecords: 15000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-16',
    name: 'Standard Quotations Configuration Tier 16',
    enabled: true,
    version: '2.4.16',
    description: 'Enterprise operational settings for quotations tier 16 management.',
    maxRecords: 16000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-17',
    name: 'Standard Quotations Configuration Tier 17',
    enabled: true,
    version: '2.4.17',
    description: 'Enterprise operational settings for quotations tier 17 management.',
    maxRecords: 17000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-18',
    name: 'Standard Quotations Configuration Tier 18',
    enabled: true,
    version: '2.4.18',
    description: 'Enterprise operational settings for quotations tier 18 management.',
    maxRecords: 18000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-19',
    name: 'Standard Quotations Configuration Tier 19',
    enabled: true,
    version: '2.4.19',
    description: 'Enterprise operational settings for quotations tier 19 management.',
    maxRecords: 19000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-20',
    name: 'Standard Quotations Configuration Tier 20',
    enabled: true,
    version: '2.4.20',
    description: 'Enterprise operational settings for quotations tier 20 management.',
    maxRecords: 20000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-21',
    name: 'Standard Quotations Configuration Tier 21',
    enabled: true,
    version: '2.4.21',
    description: 'Enterprise operational settings for quotations tier 21 management.',
    maxRecords: 21000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-22',
    name: 'Standard Quotations Configuration Tier 22',
    enabled: true,
    version: '2.4.22',
    description: 'Enterprise operational settings for quotations tier 22 management.',
    maxRecords: 22000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-23',
    name: 'Standard Quotations Configuration Tier 23',
    enabled: true,
    version: '2.4.23',
    description: 'Enterprise operational settings for quotations tier 23 management.',
    maxRecords: 23000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-24',
    name: 'Standard Quotations Configuration Tier 24',
    enabled: true,
    version: '2.4.24',
    description: 'Enterprise operational settings for quotations tier 24 management.',
    maxRecords: 24000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-25',
    name: 'Standard Quotations Configuration Tier 25',
    enabled: true,
    version: '2.4.25',
    description: 'Enterprise operational settings for quotations tier 25 management.',
    maxRecords: 25000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-26',
    name: 'Standard Quotations Configuration Tier 26',
    enabled: true,
    version: '2.4.26',
    description: 'Enterprise operational settings for quotations tier 26 management.',
    maxRecords: 26000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-27',
    name: 'Standard Quotations Configuration Tier 27',
    enabled: true,
    version: '2.4.27',
    description: 'Enterprise operational settings for quotations tier 27 management.',
    maxRecords: 27000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-28',
    name: 'Standard Quotations Configuration Tier 28',
    enabled: true,
    version: '2.4.28',
    description: 'Enterprise operational settings for quotations tier 28 management.',
    maxRecords: 28000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-29',
    name: 'Standard Quotations Configuration Tier 29',
    enabled: true,
    version: '2.4.29',
    description: 'Enterprise operational settings for quotations tier 29 management.',
    maxRecords: 29000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-30',
    name: 'Standard Quotations Configuration Tier 30',
    enabled: true,
    version: '2.4.30',
    description: 'Enterprise operational settings for quotations tier 30 management.',
    maxRecords: 30000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-31',
    name: 'Standard Quotations Configuration Tier 31',
    enabled: true,
    version: '2.4.31',
    description: 'Enterprise operational settings for quotations tier 31 management.',
    maxRecords: 31000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-32',
    name: 'Standard Quotations Configuration Tier 32',
    enabled: true,
    version: '2.4.32',
    description: 'Enterprise operational settings for quotations tier 32 management.',
    maxRecords: 32000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-33',
    name: 'Standard Quotations Configuration Tier 33',
    enabled: true,
    version: '2.4.33',
    description: 'Enterprise operational settings for quotations tier 33 management.',
    maxRecords: 33000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-34',
    name: 'Standard Quotations Configuration Tier 34',
    enabled: true,
    version: '2.4.34',
    description: 'Enterprise operational settings for quotations tier 34 management.',
    maxRecords: 34000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
  {
    id: 'quotations-cfg-35',
    name: 'Standard Quotations Configuration Tier 35',
    enabled: true,
    version: '2.4.35',
    description: 'Enterprise operational settings for quotations tier 35 management.',
    maxRecords: 35000,
    retryAttempts: 3,
    timeoutMs: 5000,
    auditEnabled: true,
  },
];

export const defaultQuotationsRules: QuotationsRule[] = [
  {
    id: 'quotations-rule-1',
    code: 'RUL_QUOTATIONS_001',
    name: 'Validate Quotations Business Policy 1',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 1.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-2',
    code: 'RUL_QUOTATIONS_002',
    name: 'Validate Quotations Business Policy 2',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 2.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'quotations-rule-3',
    code: 'RUL_QUOTATIONS_003',
    name: 'Validate Quotations Business Policy 3',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 3.',
    severity: 'high',
    active: true,
  },
  {
    id: 'quotations-rule-4',
    code: 'RUL_QUOTATIONS_004',
    name: 'Validate Quotations Business Policy 4',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 4.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'quotations-rule-5',
    code: 'RUL_QUOTATIONS_005',
    name: 'Validate Quotations Business Policy 5',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 5.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-6',
    code: 'RUL_QUOTATIONS_006',
    name: 'Validate Quotations Business Policy 6',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 6.',
    severity: 'high',
    active: true,
  },
  {
    id: 'quotations-rule-7',
    code: 'RUL_QUOTATIONS_007',
    name: 'Validate Quotations Business Policy 7',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 7.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-8',
    code: 'RUL_QUOTATIONS_008',
    name: 'Validate Quotations Business Policy 8',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 8.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'quotations-rule-9',
    code: 'RUL_QUOTATIONS_009',
    name: 'Validate Quotations Business Policy 9',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 9.',
    severity: 'high',
    active: true,
  },
  {
    id: 'quotations-rule-10',
    code: 'RUL_QUOTATIONS_010',
    name: 'Validate Quotations Business Policy 10',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 10.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'quotations-rule-11',
    code: 'RUL_QUOTATIONS_011',
    name: 'Validate Quotations Business Policy 11',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 11.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-12',
    code: 'RUL_QUOTATIONS_012',
    name: 'Validate Quotations Business Policy 12',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 12.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'quotations-rule-13',
    code: 'RUL_QUOTATIONS_013',
    name: 'Validate Quotations Business Policy 13',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 13.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-14',
    code: 'RUL_QUOTATIONS_014',
    name: 'Validate Quotations Business Policy 14',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 14.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'quotations-rule-15',
    code: 'RUL_QUOTATIONS_015',
    name: 'Validate Quotations Business Policy 15',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 15.',
    severity: 'high',
    active: true,
  },
  {
    id: 'quotations-rule-16',
    code: 'RUL_QUOTATIONS_016',
    name: 'Validate Quotations Business Policy 16',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 16.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'quotations-rule-17',
    code: 'RUL_QUOTATIONS_017',
    name: 'Validate Quotations Business Policy 17',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 17.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-18',
    code: 'RUL_QUOTATIONS_018',
    name: 'Validate Quotations Business Policy 18',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 18.',
    severity: 'high',
    active: true,
  },
  {
    id: 'quotations-rule-19',
    code: 'RUL_QUOTATIONS_019',
    name: 'Validate Quotations Business Policy 19',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 19.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-20',
    code: 'RUL_QUOTATIONS_020',
    name: 'Validate Quotations Business Policy 20',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 20.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'quotations-rule-21',
    code: 'RUL_QUOTATIONS_021',
    name: 'Validate Quotations Business Policy 21',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 21.',
    severity: 'high',
    active: true,
  },
  {
    id: 'quotations-rule-22',
    code: 'RUL_QUOTATIONS_022',
    name: 'Validate Quotations Business Policy 22',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 22.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'quotations-rule-23',
    code: 'RUL_QUOTATIONS_023',
    name: 'Validate Quotations Business Policy 23',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 23.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-24',
    code: 'RUL_QUOTATIONS_024',
    name: 'Validate Quotations Business Policy 24',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 24.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'quotations-rule-25',
    code: 'RUL_QUOTATIONS_025',
    name: 'Validate Quotations Business Policy 25',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 25.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-26',
    code: 'RUL_QUOTATIONS_026',
    name: 'Validate Quotations Business Policy 26',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 26.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'quotations-rule-27',
    code: 'RUL_QUOTATIONS_027',
    name: 'Validate Quotations Business Policy 27',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 27.',
    severity: 'high',
    active: true,
  },
  {
    id: 'quotations-rule-28',
    code: 'RUL_QUOTATIONS_028',
    name: 'Validate Quotations Business Policy 28',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 28.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'quotations-rule-29',
    code: 'RUL_QUOTATIONS_029',
    name: 'Validate Quotations Business Policy 29',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 29.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-30',
    code: 'RUL_QUOTATIONS_030',
    name: 'Validate Quotations Business Policy 30',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 30.',
    severity: 'high',
    active: true,
  },
  {
    id: 'quotations-rule-31',
    code: 'RUL_QUOTATIONS_031',
    name: 'Validate Quotations Business Policy 31',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 31.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-32',
    code: 'RUL_QUOTATIONS_032',
    name: 'Validate Quotations Business Policy 32',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 32.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'quotations-rule-33',
    code: 'RUL_QUOTATIONS_033',
    name: 'Validate Quotations Business Policy 33',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 33.',
    severity: 'high',
    active: true,
  },
  {
    id: 'quotations-rule-34',
    code: 'RUL_QUOTATIONS_034',
    name: 'Validate Quotations Business Policy 34',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 34.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'quotations-rule-35',
    code: 'RUL_QUOTATIONS_035',
    name: 'Validate Quotations Business Policy 35',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 35.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-36',
    code: 'RUL_QUOTATIONS_036',
    name: 'Validate Quotations Business Policy 36',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 36.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'quotations-rule-37',
    code: 'RUL_QUOTATIONS_037',
    name: 'Validate Quotations Business Policy 37',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 37.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-38',
    code: 'RUL_QUOTATIONS_038',
    name: 'Validate Quotations Business Policy 38',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 38.',
    severity: 'medium',
    active: true,
  },
  {
    id: 'quotations-rule-39',
    code: 'RUL_QUOTATIONS_039',
    name: 'Validate Quotations Business Policy 39',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 39.',
    severity: 'high',
    active: true,
  },
  {
    id: 'quotations-rule-40',
    code: 'RUL_QUOTATIONS_040',
    name: 'Validate Quotations Business Policy 40',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 40.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'quotations-rule-41',
    code: 'RUL_QUOTATIONS_041',
    name: 'Validate Quotations Business Policy 41',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 41.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-42',
    code: 'RUL_QUOTATIONS_042',
    name: 'Validate Quotations Business Policy 42',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 42.',
    severity: 'high',
    active: true,
  },
  {
    id: 'quotations-rule-43',
    code: 'RUL_QUOTATIONS_043',
    name: 'Validate Quotations Business Policy 43',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 43.',
    severity: 'low',
    active: true,
  },
  {
    id: 'quotations-rule-44',
    code: 'RUL_QUOTATIONS_044',
    name: 'Validate Quotations Business Policy 44',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 44.',
    severity: 'critical',
    active: true,
  },
  {
    id: 'quotations-rule-45',
    code: 'RUL_QUOTATIONS_045',
    name: 'Validate Quotations Business Policy 45',
    category: 'quotations_validation',
    expression: 'record.value != null && record.status != "Archived"',
    errorMessage: 'Quotations record fails compliance policy check 45.',
    severity: 'high',
    active: true,
  },
];
